
package actividadcajero;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {

    int Contador=3;
    String NIP="1235";
    public Login() {
        initComponents();
        this.setLocationRelativeTo(this);
        SetImageLabel(imgLogin,"src/imagenes/login.jpg");
        SetImageLabel(imgCaja,"src/imagenes/img.png");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblNIP = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnEntrar1 = new javax.swing.JButton();
        lblCajero = new javax.swing.JLabel();
        txtNIP = new javax.swing.JTextField();
        imgLogin = new javax.swing.JLabel();
        imgCaja = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        lblLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblLogin.setText("Login");
        jPanel1.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 80, 47));

        lblNIP.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblNIP.setText("NIP:");
        jPanel1.add(lblNIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 44, 35));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 106, 39));

        btnEntrar1.setText("Entrar");
        btnEntrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrar1MouseClicked(evt);
            }
        });
        btnEntrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 106, 39));

        lblCajero.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        lblCajero.setForeground(new java.awt.Color(255, 255, 255));
        lblCajero.setText("Cajero automático");
        lblCajero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblCajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 160, 30));

        txtNIP.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        txtNIP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNIPKeyTyped(evt);
            }
        });
        jPanel1.add(txtNIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 126, 35));
        jPanel1.add(imgLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 210, 450));
        jPanel1.add(imgCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 100, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEntrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrar1ActionPerformed
        
    }//GEN-LAST:event_btnEntrar1ActionPerformed

    private void btnEntrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrar1MouseClicked

        if(txtNIP.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(this,"No se ingreso NIP\nNo se reducen los intentos maximos","ERROR",JOptionPane.ERROR_MESSAGE);
           txtNIP.setText(""); 
        }  
        else if(!txtNIP.getText().trim().equals(NIP)){
            Contador--;
            JOptionPane.showMessageDialog(this,"NIP incorrecto\n"+Contador+" intentos restantes","ERROR",JOptionPane.ERROR_MESSAGE);
            txtNIP.setText("");
        }else if(txtNIP.getText().trim().equals(NIP)){
            txtNIP.setText("");
            JOptionPane.showMessageDialog(this,"Bienvenido","Inicio de sesion",1);
            Contador=3;
            MenuCajero menu=new MenuCajero();
            menu.setVisible(true);
            this.setVisible(false);

        }
        if(Contador==0){
            JOptionPane.showMessageDialog(this,"Intentos maximos superados","Bloqueo de sesion",1);
            System.exit(0);
        }
        
    }//GEN-LAST:event_btnEntrar1MouseClicked

    private void txtNIPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNIPKeyTyped
        int key = evt.getKeyChar();
        
        boolean numeros = key >48 && key <=57;
        if(txtNIP.getText().trim().length()>3||!numeros){
            evt.consume();
        }
        
        
    }//GEN-LAST:event_txtNIPKeyTyped

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    private void SetImageLabel(JLabel labelName,String root){
        ImageIcon image = new ImageIcon(root);
        ImageIcon icon = new ImageIcon(
                    image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }
        
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel imgCaja;
    private javax.swing.JLabel imgLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCajero;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNIP;
    private javax.swing.JTextField txtNIP;
    // End of variables declaration//GEN-END:variables
}
